name: Deploy to Azure

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Azure CLI
        uses: azure/login@v1
        with:
          # The following parameters are specific to your Azure environment
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          allow-no-subscriptions: true  # Optional
          federated-token: ${{ secrets.AZURE_FEDERATED_TOKEN }}

      # Add subsequent steps here to interact with Azure
      - name: 'Run Azure CLI command'
        run: |
          az group show --name $RESOURCE_GROUP
